[package]
name = "samson-lol"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.3"
log = "0.4.17"
percent-encoding = "2.2.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
rocket = "0.5.0-rc.2"
